### ISSUE TITLE
Checkpoint 1

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [BHesselbacher/budgetTracker#1]
Please use this issue to let me know when checkpoint 1 is ready for review.

**Comment by BHesselbacher** [comment]
@pawaitemadisoncollege,

I believe that my checkpoint 1 is ready for review.

**Comment by pawaitemadisoncollege** [comment]
Hi @BHesselbacher! Following are my notes from a review of CP1:

**Problem statement**

- [ ] Your problem statement is clearly written, however, I'm curious what value this brings as there are many services that provide this information. I think my banks, credit unions, and credit card companies all provide a breakdown of spending in various categories. Finance services like quickbooks can do this as well...  Can you get specific about what existing apps do not do that your application will? 
- [ ] Be sure to add to the tools and tech as you go so that anyone reviewing this can understand all the tech involved (think of prospective employers, especially!)
- [ ] Have you identified a restful api to consume yet? This may also inform your user stories below.

**user stories** You have a good start here with the core functionality.

- [ ] Your project should demonstrate full CRUD, I think you current stories cover everything except delete. Is there a meaningful delete scenario that you could add?
- [ ] Your project should demonstrate using auth with cognito - can you add meaningful sign up/login/logout stories?
- [ ] Will the user be able to control categories or types of inflow/outflow or are these all predefined?
- [ ] One of the project requirements is for multiple one-to-many relationships. Do your stories as defined meet that requirement?

**project plan**

- [ ] This lacks detail. I recommend identifying which user story/ies you will complete in a given week and detailing out the tasks needed to complete that story.  The fat bike trail reports demo project has a sample plan to get you started. 

**screen design** The screen design appears to match the current list of user stories. I appreciate the simplicity of hand-drawn screens! 

- [ ] After updating user stories based on the feedback above, add screen design to go with those stories.

**reflection statements/time log** 

- [ ] This should reflect all time spent in class - on weekly work and your indie project.  This seems to be missing any sort of detail that might be useful in understanding what you are doing and how long it is taking. 

**other**

I notice you have a .gitignore file already - be sure add include any files that contain sensitive information so they don't end up visible to everyone in GitHub. 

Please respond to this issue when the items above are addressed and I'll review and provide additional feedback. Do you have any questions?
